---
title: "LIBRA Complete Case Analysis"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r setting}
library(ggpubr)
library(missForest)

source('workflow/scripts/config.R')
source(CRS_FN)
source(LIBRA_RECODE_FN)

clinical_raw <- readRDS(file.path(DATA_INTERMEDIATE_PATH, "PREVENTAD_clinical_raw.rds"))
lifestyle_raw <- readRDS(file.path(DATA_INTERMEDIATE_PATH, "PREVENTAD_lifestyle_raw.rds"))
dat_libra <- readRDS(file.path(DATA_INTERMEDIATE_PATH, "PREVENTAD_libra_dat.rds"))
PREVENTAD_dat <- readRDS(file.path(DATA_INTERMEDIATE_PATH, "PREVENTAD_dat.rds"))
```


## Calculating LIBRA score
```{r}
dat_libra_scored <- dat_libra %>% 
  mutate(num_libra_vars = (rowSums(!is.na(.))) - 1) %>%
  mutate(complete_scores = complete.cases(.)) %>%
  mutate(score = calculate_libra(.)) %>%
  relocate(score, .after=CONP_ID) %>%
  relocate(complete_scores, .after=score) %>%
  relocate(num_libra_vars, .after=complete_scores) 

complete_libra <- dat_libra_scored %>%
  filter(complete_scores == TRUE)
```


### LIBRA scores by number of factors used for calculation
```{r}
df <- dat_libra_scored %>%
  select(CONP_ID, score, num_libra_vars, complete_scores) 

ggplot(df, aes(x=num_libra_vars)) +
  geom_bar(fill = "steelblue") +
  scale_x_continuous(labels=df$num_libra_vars, breaks=df$num_libra_vars) +
  geom_text(stat = "count",
            aes(label=after_stat(count)),
            vjust = -0.5)


# table1_gtsummary <- df %>%
#   tbl_summary(
#     by=num_cogdrisk_vars,
#     statistic = list(all_continuous() ~ "{mean} ({sd})",
#                      all_categorical() ~ "{n} ({p})")
#   )
# table1_gtsummary

completeness_summary <- df %>%
   group_by(num_libra_vars) %>%
   summarise(
     percent_cases = (n() / nrow(df)) * 100,
     min_score = min(score),
     mean_score = mean(score),
     max_score = max(score),
     sd_score = sd(score)
   )
completeness_summary

ggplot(complete_libra, aes(x=score, y=as.factor(1))) +
  geom_violin() 
```


## Missing data imputation
```{r}
colSums(is.na(dat_libra))
# Smoking, Cognitive_activity

dat_libra_imp <- lifestyle_raw %>%
  select(CONP_ID, smoking_present, epoch_score_currently) %>%
  mutate(across(!epoch_score_currently, as.factor)) %>%
  mutate(id = row_number()) %>%
  select(-CONP_ID)

imp_mf <- missForest(dat_libra_imp, verbose=TRUE, maxiter=10, ntree=100)

dat_libra_imp_mf <- cbind(imp_mf$ximp, CONP_ID=lifestyle_raw$CONP_ID) %>%
  relocate(CONP_ID) %>%
  mutate(across(!CONP_ID, as.numeric)) %>%
  mutate(smoking_present = smoking_present - 1) %>%
  select(-id)

# Update columns using imputed data
lifestyle_libra_imp <- lifestyle_raw
lifestyle_libra_imp[names(dat_libra_imp_mf)] <- dat_libra_imp_mf

dat_libra_imp_recoded <- prepare_preventad_libra(clinical_raw,
                                                 lifestyle_libra_imp)

dat_libra_imp_recoded <- dat_libra_imp_recoded %>% 
  mutate(num_libra_vars = (rowSums(!is.na(.))) - 1) %>%
  mutate(complete_scores = complete.cases(.)) %>%
  mutate(score = calculate_libra(.)) %>%
  relocate(score, .after=CONP_ID) %>%
  relocate(complete_scores, .after=score) %>%
  relocate(num_libra_vars, .after=complete_scores) 
```


### Plots of complete cases vs imputed data
```{r}
df2 <- dat_libra_scored %>%
  select(CONP_ID, score) %>%
  # left_join((complete_cogd %>%
  #              select(CONP_ID, complete_score=score)),
  #           by="CONP_ID") %>%
  left_join((dat_libra_imp_recoded %>%
               select(CONP_ID, imp_score=score)),
            by="CONP_ID") 
  
df2_longer <- df2 %>%
  pivot_longer(
    cols = c(score, imp_score),
    names_to = "method",
    values_to = "score_value"
  ) %>%
  mutate(method = recode(method,
                         "score" = "original",
                         "complete_score" = "original (complete cases)",
                         "imp_score" = "imputed"))

var_ratio <- sd(df2$imp_score) / sd(df2$score, na.rm = TRUE)

plot1 <- ggplot(df2_longer, aes(x=method, y=score_value, fill=method)) +
  geom_violin(alpha=0.7) +
  geom_boxplot(width=0.1, fill="white") +
  stat_compare_means(
    method="wilcox.test",
    label.x=1.5#,
    #label="p.format"
  ) +
  annotate(
    "text",
    x=1.5,
    y=6,
    label=paste0("SD ratio = ", round(var_ratio, 5)),
    size=4
  ) +
  ggtitle("Plot of original LIBRA (complete cases only) and imputed LIBRA")

plot1
#ggsave(plot1, filename = file.path(EDA_OUTPUT_PATH$figures, "LIBRA_completecase_imputed.png"))
```



### Scatterplots of LIBRA vs BBM (at first visit)
```{r}
df3 <- dat_libra_scored %>%
  select(CONP_ID, score) %>%
  left_join((complete_libra %>%
               select(CONP_ID, complete_score=score)),
            by="CONP_ID") %>%
  left_join((dat_libra_imp_recoded %>%
               select(CONP_ID, imp_score=score)),
            by="CONP_ID") %>%
  left_join((PREVENTAD_dat$plasma_ptau217 %>%
               group_by(CONP_ID) %>%
               slice(1)), by="CONP_ID") %>%
  select(CONP_ID, score, complete_score, imp_score, ptau217_simoa_UGOT) %>%
  pivot_longer(
    cols = c(score, complete_score, imp_score),
    names_to = "method",
    values_to = "score_value"
  ) %>%
  mutate(method = recode(method,
                         "score" = "original",
                         "complete_score" = "original (complete cases)",
                         "imp_score" = "imputed"))

ggplot(df3, aes(x=score_value, y=ptau217_simoa_UGOT, color=method)) +
  geom_point() +
  facet_wrap(~method) +
  ggtitle("Scatterplot of LIBRA scores vs ptau217 (at first visit)") +
  geom_smooth(method=lm)
  # geom_density_2d(aes(fill=..density..),z geom="raster")

ipms_bbm <- complete_libra %>%
  left_join((PREVENTAD_dat$plasma_4plex %>%
              select(CONP_ID, Study_visit_label, ptau181_simoa_UGOT,
                     GFAP_simoa_4plex, AB_ratio_simoa_4plex) %>%
              group_by(CONP_ID) %>%
              slice(1)),
            by="CONP_ID")

ggplot(ipms_bbm, aes(x=score, y=ptau181_simoa_UGOT)) +
  geom_point(shape=1) +
  ggtitle("Scatterplot of LIBRA score vs ptau181 (at first visit)") +
  geom_smooth(method="lm")

ggplot(ipms_bbm, aes(x=score, y=GFAP_simoa_4plex)) +
  geom_point(shape=1) +
  ggtitle("Scatterplot of LIBRA score vs GFAP (at first visit)") +
  geom_smooth(method="lm")

ggplot(ipms_bbm, aes(x=score, y=AB_ratio_simoa_4plex)) +
  geom_point(shape=1) +
  ggtitle("Scatterplot of LIBRA score vs AB ratio (at first visit)") +
  geom_smooth(method="lm")
```
